/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class okj_easy_graphics_graphics2d_NSprite */

#ifndef _Included_okj_easy_graphics_graphics2d_NSprite
#define _Included_okj_easy_graphics_graphics2d_NSprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setBounds
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setBounds
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setSize
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setSize
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setPosition
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setPosition
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setX
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setX
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setY
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setY
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    translate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_translate
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    translateX
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_translateX
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    translateY
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_translateY
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setOrigin
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setOrigin
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setRotation
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setRotation
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    rotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_rotate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setScale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setScale__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    setScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_setScale__JFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    scale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_scale
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getVertices
 * Signature: (J[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getVertices
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getCenterX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getCenterX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getCenterY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getCenterY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getOriginX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getOriginX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getOriginY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getOriginY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getRotation
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getRotation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getScaleX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getScaleX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    getScaleY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_okj_easy_graphics_graphics2d_NSprite_getScaleY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    isDirty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_okj_easy_graphics_graphics2d_NSprite_isDirty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSprite
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSprite_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
