/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <Sprite/SpriteProcessor.h>
/* Header for class org_ege_utils_SpriteUtils */

#ifndef _Included_org_ege_utils_SpriteUtils
#define _Included_org_ege_utils_SpriteUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ege_utils_SpriteUtils
 * Method:    getNearestSprite
 * Signature: ([III[F[FI)V
 */
JNIEXPORT void JNICALL Java_org_ege_utils_SpriteUtils_getNearestSprite___3III_3F_3FI
  (JNIEnv *, jclass, jintArray, jint, jint, jfloatArray, jfloatArray, jint);

/*
 * Class:     org_ege_utils_SpriteUtils
 * Method:    getNearestSprite
 * Signature: ([IIIFF[FI)V
 */
JNIEXPORT void JNICALL Java_org_ege_utils_SpriteUtils_getNearestSprite___3IIIFF_3FI
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jfloatArray, jint);

/*
 * Class:     org_ege_utils_SpriteUtils
 * Method:    getNearestSprite
 * Signature: ([IIFF[FI)V
 */
JNIEXPORT void JNICALL Java_org_ege_utils_SpriteUtils_getNearestSprite___3IIFF_3FI
  (JNIEnv *, jclass, jintArray, jint, jfloat, jfloat, jfloatArray, jint);

/*
 * Class:     org_ege_utils_SpriteUtils
 * Method:    getNearestSprite
 * Signature: ([II[F[FI)V
 */
JNIEXPORT void JNICALL Java_org_ege_utils_SpriteUtils_getNearestSprite___3II_3F_3FI
  (JNIEnv *, jclass, jintArray, jint, jfloatArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
