/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class okj_easy_graphics_graphics2d_NSpriteDef */

#ifndef _Included_okj_easy_graphics_graphics2d_NSpriteDef
#define _Included_okj_easy_graphics_graphics2d_NSpriteDef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     okj_easy_graphics_graphics2d_NSpriteDef
 * Method:    equal
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_okj_easy_graphics_graphics2d_NSpriteDef_equal
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSpriteDef
 * Method:    addBounding
 * Signature: (J[FI[II)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSpriteDef_addBounding
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jintArray, jint);

/*
 * Class:     okj_easy_graphics_graphics2d_NSpriteDef
 * Method:    removeBounding
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSpriteDef_removeBounding
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     okj_easy_graphics_graphics2d_NSpriteDef
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_okj_easy_graphics_graphics2d_NSpriteDef_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NSpriteDef
 * Method:    clearBounding
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NSpriteDef_clearBounding
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
