/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <Sprite/Pol2D.h>
/* Header for class okj_easy_graphics_graphics2d_NManager */

#ifndef _Included_okj_easy_graphics_graphics2d_NManager
#define _Included_okj_easy_graphics_graphics2d_NManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     okj_easy_graphics_graphics2d_NManager
 * Method:    manage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NManager_manage
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     okj_easy_graphics_graphics2d_NManager
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_okj_easy_graphics_graphics2d_NManager_clear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
